{
 "title": "Kafka集群监控模板",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Kafka进程CPU使用率",
   "type": "graph",
   "description": "java.lang:type=OperatingSystem",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvmMemory",
     "select": [
      [
       { "params": [ "ProcessCpuLoad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "进程CPU使用率" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "description": "服务器CPU使用率",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvmMemory",
     "select": [
      [
       { "params": [ "SystemCpuLoad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU使用率" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "graph",
   "description": "java.lang:type=OperatingSystem\nLinux系统负载",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvmMemory",
     "select": [
      [
       { "params": [ "SystemLoadAverage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "系统负载" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka Topic 每秒数据量",
   "type": "graph",
   "description": "Kafka每个broker每秒中的数据量，包括__consumer_offsets topic",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "kafkaServer",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "平均每秒" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=MessagesInPerSec"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "kafkaServer",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "所有broker平均每秒" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=MessagesInPerSec"
      }
     ]
    }
   ]
  },
  {
   "title": "可用物理内存",
   "type": "graph",
   "description": "java.lang:type=OperatingSystem\n服务器可用物理内存",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvmMemory",
     "select": [
      [
       { "params": [ "FreePhysicalMemorySize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "系统剩余物理内存" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka控制器数量",
   "type": "graph",
   "description": "kafka.controller:type=KafkaController,name=ActiveControllerCount\n\nKafka控制器数量，每个集群只有一台机器为1，为1的机器是Kafka控制器Crontroller",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "activeController",
     "query": "SELECT sum(\"Value\") AS \"获取控制器数量\" FROM \"activeController\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "获取控制器数量" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka每秒拉取流量",
   "type": "graph",
   "description": "监控 kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec 指标",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafkaServer",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "每秒拉取字节数" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesOutPerSec"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka每秒进入流量",
   "type": "graph",
   "description": "监控 kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec 指标",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafkaServer",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "平均每秒进入字节数" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesInPerSec"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka生产、消费每秒请求数量",
   "type": "graph",
   "description": "监控 kafka.server:type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec 和 kafka.server:type=BrokerTopicMetrics,name=TotalProduceRequestsPerSec 指标",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafkaServer",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "每秒Fetch(获取)的请求数量" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafkaServer",
     "select": [
      [
       { "params": [ "MeanRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "每秒Producer发送的请求数量" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=TotalProduceRequestsPerSec"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka使用堆内存",
   "type": "graph",
   "description": "java.lang:type=Memory",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvmMemory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "堆内存使用" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka使用堆外内存",
   "type": "graph",
   "description": "java.lang:type=Memory",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvmMemory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "对外内存使用" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "未充分备份的分区数监控",
   "type": "graph",
   "description": "kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions\n不为0则说明有的副本跟不上leader",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "underReplicated",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "未充分备份的分区数" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka网络线程池线程平均的空闲比例",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "网络线程池空闲比例" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": " I/O 线程池线程平均的空闲比例",
   "type": "graph",
   "description": "kafka.server:type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IO空闲比例" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka生产、消费请求失败数量",
   "type": "graph",
   "description": "监控 kafka.server:type=BrokerTopicMetrics,name=FailedFetchRequestsPerSec 和 kafka.server:type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec 指标",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafkaServer",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "每秒Fetch(获取)异常的请求" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=FailedFetchRequestsPerSec"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafkaServer",
     "select": [
      [
       { "params": [ "MeanRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "每秒Producer异常的请求" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=FailedProduceRequestsPerSec"
      }
     ]
    }
   ]
  }
 ]
}